# name: rahmann, pokaan
# markdown : kramdown
# permalink: /blog/:year/:month/:day/:title

title: Rahman Blog   # your title
author: Rahmann # your name
description: Sharing Notes # your description
avatar: /images/avatar.png # change avatar

# Build Settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:title

# Pagination
paginate: 5
paginate_path: "/page:num/"
gems: [jekyll-paginate]

# Comments
### this one is to enable all page with comments. 
# disqus:
#   shortname: rahman99   # your disqus shortname

# Google Analytics
google_analytics: UA-104955265-1  # your google analytics
